"""Reviewable classification of every API endpoint.

The route-closure regression test requires exact equality with ``app.url_map``.
"""

PUBLIC_ENDPOINTS = {
    "auth.login": "public_login",
    "password_reset.forgot_password": "public_password_reset_request",
}

ACCESS_POLICY_MANIFEST = {
    **PUBLIC_ENDPOINTS,
    "auth.logout": "authenticated_self",
    "auth.change_password": "authenticated_self",
    "auth.reset_password": "admin_target_write",
    "admin.get_course_plans": "admin",
    "admin.get_courses": "admin",
    "admin.create_course": "admin",
    "admin.update_course": "admin",
    "admin.delete_course": "admin",
    "admin.get_enrollment_control": "admin",
    "admin.set_enrollment_control": "admin",
    "admin.get_enrollment_stats": "admin",
    "admin.get_pending_grades": "admin",
    "admin.get_logs": "admin",
    "admin.get_semester_configs": "admin",
    "admin.create_semester_config": "admin",
    "admin.update_semester_config": "admin",
    "admin.delete_semester_config": "admin",
    "admin.get_students": "admin",
    "admin.create_student": "admin",
    "admin.update_student": "admin",
    "admin.delete_student": "admin",
    "admin.get_teachers": "admin",
    "admin.create_teacher": "admin",
    "admin.update_teacher": "admin",
    "admin.delete_teacher": "admin",
    "audit.get_course_plan_audit_list": "admin",
    "audit.handle_course_plan": "admin_plan",
    "audit.get_overview": "admin",
    "audit.get_password_resets": "admin",
    "audit.handle_password_reset": "admin_target_write",
    "enrollment.drop_course": "student_self_plan_write",
    "enrollment.select_course": "student_self_plan_write",
    "grade.audit_grade": "admin",
    "grade.batch_record_grade": "teacher_plan_write",
    "grade.apply_modify": "teacher_owned_grade_write",
    "grade.record_grade": "teacher_plan_write",
    "stats.get_class_stats": "teacher_or_admin_plan_read",
    "stats.get_score_distribution": "teacher_or_admin_plan_read",
    "stats.export_stats": "role_and_resource_dynamic_export",
    "stats.get_gpa_trend": "student_self_or_admin",
    "student.get_available_courses": "student",
    "student.get_my_grades": "student_self",
    "student.get_my_courses": "student_self",
    "student.get_my_stats": "student_self",
    "teacher.submit_course_plan": "teacher_self_write",
    "teacher.update_course_plan": "teacher_plan_write",
    "teacher.get_teacher_course_list": "teacher",
    "teacher.get_course_grades": "teacher_plan_read",
    "teacher.get_teaching_plans": "teacher_self",
    "teacher.get_enrolled_students": "teacher_plan_read",
}
